name=CinCout
version=1.0.17
includes=iostream.hpp
author=Bojan Jurca
maintainer=Bojan Jurca <bojan@gmail.com>
sentence=Bring familiar C++ cin and cout streams to Arduino.
paragraph=Implements minimal cin and cout stream objects for Arduino.
category=Signal Input/Output
url=https://github.com/BojanJurca/cin-cout-for-Arduino
architectures=*
license=MIT

